### ISSUE TITLE
Open Git repository directly into zapp

### ISSUE THREAD

**Issue by SirusCodes** [invertase/zapp.run#44] opened 2022-07-15 12:24 UTC
**Is your feature request related to a problem? Please describe.**
Adding a clone feature so that one can directly open their repositories and work directly into it.
Maybe having a URL to open it which can be further used to create buttons in readme

**Comment by Ehesp** [comment] 2022-07-15 12:25
Duplicate of https://github.com/invertase/zapp.run/issues/2

**Closed by Ehesp** 2022-07-15 12:25 UTC
Labels: enhancement
