### ISSUE TITLE
Does not resolve pub package

### ISSUE THREAD

**Issue by rebaz94** [invertase/zapp.run#50] opened 2022-07-18 22:11 UTC
Hi
I just tested the zap and want to use a package, the analyzer working but I can't run the app.

```
Error: Couldn't resolve the package 'upstash_redis' in 'package:upstash_redis/upstash_redis.dart'.
file:///zapp/project/lib/my_app.dart:2:8: Error: Not found: 'package:upstash_redis/upstash_redis.dart'
[00:51:59] import 'package:upstash_redis/upstash_redis.dart';
file:///zapp/project/lib/my_app.dart:31:25: Error: The method 'Redis' isn't defined for the class 'MyHomePage'.
'MyHomePage' is from 'file:///zapp/project/lib/my_app.dart'.
Try correcting the name to the name of an existing method, or defining a method named 'Redis'.
final redis = Redis(
```

**Project ID**: flutter-zps06a9pt06
**Operating System & Version**: MacOS 10.15.4 (19E287)
**Browser & Version**: Chrome 103.0.5060.114

![Screen Shot 2022-07-19 at 1 02 44 AM](https://user-images.githubusercontent.com/11982812/179625226-fe37d7af-e482-431b-828a-c448a6efa540.png)

**Comment by Salakar** [comment] 2022-07-19 09:45
I saw this bug yesterday and couldn't reproduce and hoped maybe it was something I did 😅 guess not. The workaround for now is to save your project and reload the page, then build/run should pick up the package now - I will look into it again and see if I can reproduce

**Comment by Salakar** [comment] 2022-08-19 16:51
This is now fixed in the latest version that is now live, thanks

**Closed by Salakar** 2022-08-19 16:51 UTC
Labels: bug, compiler
