### ISSUE TITLE
assets folder doesn't work 

### ISSUE THREAD

**Issue by Gaurangseven** [invertase/zapp.run#84] opened 2022-09-04 15:47 UTC
**Project ID (e.g. `flutter-123456`)**: 
**Operating System & Version (e.g. `macOS Monterey 12.1`)**:
**Browser & Version (e.g. `Chrome 102.0.5005.115`)**:

### Description
Whenever I m trying to add dash images to my project assets are lost and errors like assets doesn't exists appear.

**Comment by Solido** [comment] 2022-09-07 08:05
Just to confirm that `/assets/` images are working on my side.
Can you check your conf?

**Comment by Salakar** [comment] 2022-09-07 15:11
Closing as duplicate of #76

**Closed by Salakar** 2022-09-07 15:11 UTC
Labels: bug
